### ISSUE TITLE
Shopify App v1.0

### ISSUE THREAD

**Issue by timoguin** [tiki/apps#1]
Tracking issue for Shopify v1.0 milestone:

https://github.com/tiki/apps-shopify-extensions/milestone/2

# Tasks

- [ ] tiki/apps-shopify-extensions#52
- [ ] tiki/apps-shopify-web/issues/3
- [ ] tiki/apps-shopify-extensions#44
- [ ] tiki/apps-shopify-extensions#61
- [ ] tiki/apps-shopify-web/issues/4
- [ ] tiki/apps-shopify-extensions#29
- [ ] tiki/apps-shopify-extensions#30
- [ ] tiki/apps-shopify-extensions#94
- [ ] tiki/apps-shopify-extensions#19
- [ ] tiki/apps-shopify-extensions#91
- [ ] tiki/apps-shopify-extensions#90
- [x] tiki/apps-shopify-extensions#43
- [x] tiki/apps-shopify-extensions#28

**Comment by mike-audi** [comment]
on hold until: https://github.com/tiki/core/issues/11

**Comment by ricardobrg** [comment]
@sfaria27 I am closing these shopify milestones, since it doesn't make sense to separate in mvp/1.0 at this point. When we get back to Shopify, we create a new milestone with updated planning.
