### ISSUE TITLE
Managed Rewards v0.5.0

### ISSUE THREAD

**Issue by mike-audi** [tiki/apps#11]
# Description

UI/UX improvements for [pilot](https://github.com/tiki/apps-receipt-capacitor/releases/tag/0.4.0) usability and bug fixes to address edge cases.

# Issues

- [x] tiki/capture-receipt-capacitor/issues/303
- [x] tiki/capture-receipt-capacitor/issues/348
- [x] tiki/capture-receipt-capacitor/issues/392

## Bugs

- [x] https://github.com/tiki/apps-receipt-capacitor/issues/300
- [x] https://github.com/tiki/publish-sdk-capacitor/issues/138
