### ISSUE TITLE
CLO Inbound Content Strategy

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps#19]
Planning, development, and publication of inbound content for Cashback Connections. The goal is to engage users, provide valuable information, and promote the platform. 

## Tasks

- [x] https://github.com/tiki/apps-receipt-capacitor/issues/398
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/399
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/400
