### ISSUE TITLE
Shopify App MVP

### ISSUE THREAD

**Issue by timoguin** [tiki/apps#2]
Tracking issue for Shopify MVP milestone:

https://github.com/tiki/apps-shopify-extensions/milestone/1

# Tasks

- [ ] tiki/publish-sdk-js/issues/108
- [ ] tiki/apps-shopify-extensions/issues/122
- [ ] tiki/apps-shopify-extensions#106
- [ ] tiki/apps-shopify-extensions#4
- [ ] tiki/apps-shopify-extensions#95
- [ ] tiki/apps-shopify-extensions#104
- [ ] tiki/apps-shopify-extensions#56
- [ ] tiki/apps-shopify-extensions#113
- [x] tiki/apps-shopify-extensions#3
- [x] tiki/apps-shopify-extensions#116

**Comment by mike-audi** [comment]
on hold until: https://github.com/tiki/core/issues/11

**Comment by ricardobrg** [comment]
@sfaria27 I am closing these shopify milestones, since it doesn't make sense to separate in mvp/1.0 at this point. When we get back to Shopify, we create a new milestone with updated planning.
