### ISSUE TITLE
CLO Demo app

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps#20]
Configure the example app to be used as a demo app. The first demo app should focus on UX demonstration:

### Android

- [x] tiki/apps-rewards-android/issues/30
- [x] tiki/apps-rewards-android/issues/3
- [x] tiki/apps-rewards-android/issues/31
- [x] tiki/apps-rewards-android/issues/32
- [x] tiki/apps-rewards-android/issues/33
- [x] tiki/apps-rewards-android/issues/35
- [x] tiki/apps-rewards-android/issues/36
- [x] tiki/apps-rewards-android/issues/37
- [x] tiki/apps-rewards-android/issues/38
- [x] tiki/apps-rewards-android/issues/53
- [x] tiki/apps-rewards-android/issues/60
- [x] tiki/apps-rewards-android/issues/61

### iOS

- [x] tiki/apps-rewards-ios/issues/20
- [x] tiki/apps-rewards-ios/issues/21
- [x] tiki/apps-rewards-ios/issues/22
- [x] tiki/apps-rewards-ios/issues/23
- [x] tiki/apps-rewards-ios/issues/24
- [x] tiki/apps-rewards-ios/issues/25
- [x] tiki/apps-rewards-ios/issues/26
- [x] tiki/apps-rewards-ios/issues/27
- [x] tiki/apps-rewards-ios/issues/28
