### ISSUE TITLE
Functional Android Rewards App

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#25]
### Description

The Android Rewards app currently is a UX demo app, without any functionalities. 

The first step to make it functional is to integrate it with the Capture Receipt SDK, which provides features for adding accounts and scraping receipt data from email, retailer accounts and physicial receipts. 

### Issues

- [x] tiki/apps-rewards-android#66
- [x] tiki/apps-rewards-android#67
- [x] tiki/apps-rewards-android#68
- [x] tiki/apps-rewards-android#69
- [x] tiki/apps-rewards-android#70
- [x] tiki/apps-rewards-android#71
- [x] tiki/apps-rewards-android#72
- [x] tiki/apps-rewards-android#73
