### ISSUE TITLE
Functional iOS Rewards App

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#26]
### Description

The iOS Rewards app currently is a UX demo app, without any functionalities.

The first step to make it functional is to integrate it with the Capture Receipt SDK, which provides features for adding accounts and scraping receipt data from email, retailer accounts and physicial receipts.

### Issues

- [x] tiki/apps-rewards-ios/issues/42
- [x]  tiki/apps-rewards-ios/issues/43
- [x]  tiki/apps-rewards-ios/issues/44
- [x]  tiki/apps-rewards-ios/issues/45
- [x]  tiki/apps-rewards-ios/issues/46
- [x]  tiki/apps-rewards-ios/issues/47
- [x]  tiki/apps-rewards-ios/issues/48
- [x]  tiki/apps-rewards-ios/issues/49
- [x] tiki/capture-receipt-ios/issues/22
