### ISSUE TITLE
Rewards app API update for iOS

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#33]
### Description

 Make the TIKI Rewards ready for release, missing only the connection with the backend services. 

### Issues

- [x] tiki/apps-rewards-ios#64
- [x] tiki/apps-rewards-ios#65
- [x] tiki/apps-rewards-ios#67
- [x] tiki/apps-rewards-ios#68
- [x] tiki/apps-rewards-ios#69
- [x] tiki/apps-rewards-ios#72
- [x] tiki/apps-rewards-ios#73
- [x] tiki/apps-rewards-ios#85
- [x] tiki/apps-rewards-ios#76
- [x] tiki/apps-rewards-ios#77
- [x] tiki/apps-rewards-ios#79
- [x] tiki/apps-rewards-ios#80
- [x] tiki/apps-rewards-ios#81
- [x] tiki/apps-rewards-ios#82
