### ISSUE TITLE
Rewards app API update for Android

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#34]
### Description

Make the TIKI Rewards ready for release, missing only the connection with the backend services. 

- [x] tiki/apps-rewards-android#84
- [x] tiki/apps#50
- [x] tiki/apps-rewards-android#85
- [x] tiki/apps-rewards-android#86
- [x] tiki/apps-rewards-android#87
- [x] tiki/apps-rewards-android#88
- [x] tiki/apps-rewards-android#89
- [x] tiki/apps-rewards-android#90 
- [x] tiki/apps-rewards-android#96
- [ ] Define new test cases to increase coverage
- [ ] Implement new test cases
- [ ] Github docs action
- [ ] Github test action
- [ ] Github release action
- [ ] Publish the example app to Play Store Beta
