### ISSUE TITLE
Managed Rewards Pilot

### ISSUE THREAD

**Issue by mike-audi** [tiki/apps#4]
### Description

The pilot is centered around linking an email account + 1 or more additional retailer accounts to earn consistent passive income monthly. Key features: gmail linking, retailer linking, simplified UX.

**The pilot is for 5,000 users, on both iOS and Android**

### Issues:

- [x] https://github.com/tiki/capture-receipt-capacitor/issues/346
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/348
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/340
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/256
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/255
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/334
- [x] tiki/apps-receipt-capacitor#219
- [x] tiki/capture-receipt-capacitor#316
- [x] tiki/apps-receipt-capacitor#239
- [x] tiki/capture-receipt-capacitor/issues/318
- [x] tiki/apps-receipt-capacitor#217
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/335
- [x] tiki/capture-receipt-capacitor#288
- [x] tiki/capture-receipt-capacitor#289
- [x] tiki/capture-receipt-capacitor#309
- [x] tiki/capture-receipt-capacitor#312
- [x] tiki/capture-receipt-capacitor#313
- [x] tiki/capture-receipt-capacitor#310
- [x] tiki/capture-receipt-capacitor#311
- [x] tiki/capture-receipt-capacitor#314
- [x] tiki/apps-receipt-capacitor#204
- [x] tiki/capture-receipt-capacitor#296
- [x] tiki/apps-receipt-capacitor#207
- [x] tiki/capture-receipt-capacitor#275
- [x] tiki/capture-receipt-capacitor#295
- [x] tiki/capture-receipt-capacitor#298
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/225
- [x] tiki/capture-receipt-capacitor#244
- [x] tiki/capture-receipt-capacitor#84
- [x] tiki/apps-receipt-capacitor#197
- [x] tiki/apps-receipt-capacitor#198
- [x] tiki/apps-receipt-capacitor#199
- [x] tiki/apps-receipt-capacitor#200
- [x] tiki/apps-receipt-capacitor#201
- [x] tiki/apps-receipt-capacitor#202
- [x] tiki/apps-receipt-capacitor#203
- [x] tiki/apps-receipt-capacitor#205
- [x] tiki/apps-receipt-capacitor#206
- [x] tiki/capture-receipt-capacitor#272
- [x] tiki/apps-receipt-capacitor#192
- [x] tiki/apps-receipt-capacitor#186
- [x] tiki/apps-receipt-capacitor#195
- [x] tiki/apps-receipt-capacitor#193
- [x] tiki/capture-receipt-capacitor#180
- [x] tiki/capture-receipt-capacitor#273
- [x] tiki/capture-receipt-capacitor#242

**Comment by timoguin** [comment]
0.4.0. has been released: https://www.npmjs.com/package/@mytiki/receipt-capacitor
