### ISSUE TITLE
Apps Rewards iOS CLO features

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#62]
### Description

Upgrade apps rewards with the CLO features and publish to testflight.

### Issues

- [x] tiki/apps-rewards-ios/issues/85
- [x] tiki/apps-rewards-ios/issues/72
- [x] tiki/apps-rewards-ios/issues/73
- [x] tiki/apps-rewards-ios/issues/80
- [x] tiki/apps-rewards-ios/issues/81
