### ISSUE TITLE
Apps Rewards Android CLO features

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#63]
### Description

Upgrade apps rewards with the CLO features and publish to play store connect

### Issues

- [x] tiki/apps-rewards-android/issues/96
- [x] #64
- [x] tiki/apps-rewards-android/issues/97
- [x] tiki/apps-rewards-android/issues/90
- [x] tiki/apps-rewards-android/issues/45
- [x] tiki/apps-rewards-android/issues/54
- [x] tiki/apps-rewards-android/issues/65
