### ISSUE TITLE
Managed Rewards v0.4.1

### ISSUE THREAD

**Issue by mike-audi** [tiki/apps#9]
### Description
1) Adds iOS compatibility to [pilot](https://github.com/tiki/apps-receipt-capacitor/releases/tag/0.4.0)
2) Bug fixes to improve Android data capture reliability. 
3) Vue2 compatibility

### Issues

- [x] https://github.com/tiki/publish-sdk-ios/issues/271
- [ ] tiki/apps-receipt-capacitor#164
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/281
- [x] https://github.com/tiki/capture-receipt-capacitor/pull/372
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/257
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/384
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/355
- [x] tiki/capture-receipt-capacitor#380
- [x] tiki/publish-data-rest#11
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/347
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/349
- [x] tiki/capture-receipt-capacitor#315
- [x] tiki/capture-receipt-capacitor#297
- [x] https://github.com/tiki/apps-receipt-capacitor/issues/277
- [x] https://github.com/tiki/capture-receipt-capacitor/issues/379
